export const ALL_APPOINTMENTS_REQUEST = "ALL_APPOINTMENTS_REQUEST";
export const ALL_APPOINTMENTS_SUCCESS = "ALL_APPOINTMENTS_SUCCESS";
export const ALL_APPOINTMENTS_FAIL = "ALL_APPOINTMENTS_FAIL";
export const ALL_APPOINTMENTS_RESET = "ALL_APPOINTMENTS_RESET";

export const NEW_APPOINTMENT_REQUEST = "NEW_APPOINTMENT_REQUEST";
export const NEW_APPOINTMENT_SUCCESS = "NEW_APPOINTMENT_SUCCESS";
export const NEW_APPOINTMENT_RESET = "NEW_APPOINTMENT_RESET";
export const NEW_APPOINTMENT_FAIL = "NEW_APPOINTMENT_FAIL";

export const APPOINTMENT_DETAILS_REQUEST = "APPOINTMENT_DETAILS_REQUEST";
export const APPOINTMENT_DETAILS_SUCCESS = "APPOINTMENT_DETAILS_SUCCESS";
export const APPOINTMENT_DETAILS_FAIL = "APPOINTMENT_DETAILS_FAIL";

export const UPDATE_APPOINTMENT_REQUEST = "UPDATE_APPOINTMENT_REQUEST";
export const UPDATE_APPOINTMENT_SUCCESS = "UPDATE_APPOINTMENT_SUCCESS";
export const UPDATE_APPOINTMENT_RESET = "UPDATE_APPOINTMENT_RESET";
export const UPDATE_APPOINTMENT_FAIL = "UPDATE_APPOINTMENT_FAIL";

export const DELETE_APPOINTMENT_REQUEST = "DELETE_APPOINTMENT_REQUEST";
export const DELETE_APPOINTMENT_SUCCESS = "DELETE_APPOINTMENT_SUCCESS";
export const DELETE_APPOINTMENT_FAIL = "DELETE_APPOINTMENT_FAIL";
export const DELETE_APPOINTMENT_RESET = "DELETE_APPOINTMENT_RESET";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
