export const REGISTER_COMPANY_REQUEST = "REGISTER_COMPANY_REQUEST";
export const REGISTER_COMPANY_SUCCESS = "REGISTER_COMPANY_SUCCESS";
export const REGISTER_COMPANY_RESET = "REGISTER_COMPANY_RESET";
export const REGISTER_COMPANY_FAIL = "REGISTER_COMPANY_FAIL";

export const UPDATE_COMPANY_REQUEST = "UPDATE_COMPANY_REQUEST";
export const UPDATE_COMPANY_SUCCESS = "UPDATE_COMPANY_SUCCESS";
export const UPDATE_COMPANY_RESET = "UPDATE_COMPANY_RESET";
export const UPDATE_COMPANY_FAIL = "UPDATE_COMPANY_FAIL";

export const EDIT_COMPANY_REQUEST = "EDIT_COMPANY_REQUEST";
export const EDIT_COMPANY_SUCCESS = "EDIT_COMPANY_SUCCESS";
export const EDIT_COMPANY_RESET = "EDIT_COMPANY_RESET";
export const EDIT_COMPANY_FAIL = "EDIT_COMPANY_FAIL";

export const COMPANY_DETAILS_REQUEST = "COMPANY_DETAILS_REQUEST";
export const COMPANY_DETAILS_SUCCESS = "COMPANY_DETAILS_SUCCESS";
export const COMPANY_DETAILS_FAIL = "COMPANY_DETAILS_FAIL";

export const DELETE_COMPANY_REQUEST = "DELETE_COMPANY_REQUEST";
export const DELETE_COMPANY_SUCCESS = "DELETE_COMPANY_SUCCESS";
export const DELETE_COMPANY_FAIL = "DELETE_COMPANY_FAIL";
export const DELETE_COMPANY_RESET = "DELETE_COMPANY_RESET";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
