export const ALL_QUOTATIONS_REQUEST = "ALL_QUOTATIONS_REQUEST";
export const ALL_QUOTATIONS_SUCCESS = "ALL_QUOTATIONS_SUCCESS";
export const ALL_QUOTATIONS_FAIL = "ALL_QUOTATIONS_FAIL";
export const ALL_QUOTATIONS_RESET = "ALL_QUOTATIONS_RESET";

export const NEW_QUOTATION_REQUEST = "NEW_QUOTATION_REQUEST";
export const NEW_QUOTATION_SUCCESS = "NEW_QUOTATION_SUCCESS";
export const NEW_QUOTATION_RESET = "NEW_QUOTATION_RESET";
export const NEW_QUOTATION_FAIL = "NEW_QUOTATION_FAIL";

export const QUOTATION_DETAILS_REQUEST = "QUOTATION_DETAILS_REQUEST";
export const QUOTATION_DETAILS_SUCCESS = "QUOTATION_DETAILS_SUCCESS";
export const QUOTATION_DETAILS_FAIL = "QUOTATION_DETAILS_FAIL";

export const UPDATE_QUOTATION_REQUEST = "UPDATE_QUOTATION_REQUEST";
export const UPDATE_QUOTATION_SUCCESS = "UPDATE_QUOTATION_SUCCESS";
export const UPDATE_QUOTATION_RESET = "UPDATE_QUOTATION_RESET";
export const UPDATE_QUOTATION_FAIL = "UPDATE_QUOTATION_FAIL";

export const DELETE_QUOTATION_REQUEST = "DELETE_QUOTATION_REQUEST";
export const DELETE_QUOTATION_SUCCESS = "DELETE_QUOTATION_SUCCESS";
export const DELETE_QUOTATION_FAIL = "DELETE_QUOTATION_FAIL";
export const DELETE_QUOTATION_RESET = "DELETE_QUOTATION_RESET";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
